<?php

/**
 * English translation
 */

return [
    
    /*  Form/Route -----------------------------------------------------------  */
    ':keyword'                  => 'keyword',
    ':login'                    => 'login',
    ':registration'             => 'signup',
    ':tutorial'                 => 'tutorial',
    
    'Home'                      => 'Home',
    'Login'                     => 'Login',
    'Login/Registration'        => 'Login/Registration',
    'Registration'              => 'Sign Up',
    'UseYourAccount'            => 'Use your account',
     'e-mail'                    => 'e-mail',
    'email'                     => 'email',
    'EnterEmail'                => 'Enter your e-mail address',
    'EnterPassword'             => 'Enter your password',
    'ForgotPassword'            => 'Forgot your password?',
    'PasswordRecoveryLink'      => 'Create a new one.',
    'DontHaveAccount'           => 'Do not have an account?',
    'DontHaveAccountText'       => 'Create account quickly and easily. By creating an account, you will beenabled to placing an ad, ad tracking and get other information.',
    'MakeAccountLink'           => 'Create an account',
    'LoginError'                => 'Login Error',
    'LoginErrorInfo'            => 'There is some error with your signing. User or password is not valid. Please enter a valid credential data and try again!',
    'LoginSuccess'              => 'Login Success',
    'LoginSuccessInfo'          => 'Now you have successfully logged. Please wait for automatic redirection, or click on the button below to return to the home page.',
    /* Registration ----------------------------------------------------------- */
    'ReenterPassword'           => 'Repeat password',
    'name'                      => 'name',
    'EnterFirstName'            => 'Enter your first name',
    'EnterLastName'             => 'Enter your last name',
    'FirstName'                 => 'First name',
    'LastName'                  => 'Last name',
    'Email'                     => 'Email',
    'Password'                  => 'Lozinka',
    'Phone'                     => 'Phone number',
    'RPassword'                 => 'Repeated password',
    'UserRegisterSuccessfully'  => 'You have successfully completed the registration process. In order for your account to be active, please click on the link sent to your email to verify your email address.',
    'UserLoginSuccessfully'     => 'You are successfuly login. Please wait.',
    'EnterPhone'                => 'Enter your phone number',
    'first_name'                => 'first_name',
    'last_name'                 => 'last_name',
    'phone'                     => 'phone',
    'password'                  => 'password',
    'rpassword'                 => 'rpassword',
    /* Designer --------------------------------------------------------------- */
    'NewProject'                => 'New Project',
    'SaveProject'               => 'Save Project',
    'SaveProjectAsNew'          => 'Save as new',
    'GenerateCode'              => 'Generate Code',
    'UncategorizedError'        => 'There is an uncategorized error processing your request. Please contact our support.',
    'DesignSaved'               => 'Project is saved successfully.',
    'TitleError'                => 'Project title is required and can not be a empty. Please add your project name.',
    'titleplaceholder'          => 'add project title',
    'YourDesigns'               => 'Your designs',
    'DesignTitle'               => 'Design Title',
    'Date'                      => 'Date',
    'History'                   => 'History',
    'SignOut'                   => 'Sign Out',
    'ContactUs'                 => 'Contact us',
    'TermsOfUse'                => 'Terms of use',
    'Support'                   => 'Support',
    'Tutorial'                  => 'Tutorial',
    'Remove'                    => 'Remove',
    'AddSearchkeywords'         => 'add search keywords...',
    'SearchBydate'              => 'search by date...',
    'FilterIncluded'            => 'Filter is included!',
    'ErrorPhone'                => 'Phone number is not a valid. Please add valid phone number.',
    
    /* Registration ----------------------------------------------------------- */
    'ReenterPassword'           => 'Repeat password',
    'name'                      => 'name',
    'EnterFirstName'            => 'Enter your first name',
    'EnterLastName'             => 'Enter your last name',
    'FirstName'                 => 'First name',
    'LastName'                  => 'Last name',
    'Email'                     => 'Email',
    'Password'                  => 'Lozinka',
    'Phone'                     => 'Phone number',
    'RPassword'                 => 'Repeated password',
    'UserRegisterSuccessfully'  => 'You have successfully completed the registration process. In order for your account to be active, please click on the link sent to your email to verify your email address.',
    'UserLoginSuccessfully'     => 'You are successfuly login. Please wait.',
    'EnterPhone'                => 'Enter your phone number',
    'first_name'                => 'first_name',
    'last_name'                 => 'last_name',
    'phone'                     => 'phone',
    'password'                  => 'password',
    'rpassword'                 => 'rpassword',
    'RegistrationSuccess'       => 'You are successfully registered.',
    'successreginfo'            => 'Please wait to web administrator activate your account.',
    
    'PageNotFound'              => 'Page not found. Please check url and try again!',
    
    /* Pages ------------------------------------------------------------------ */
    'VisualDesigner'            => 'About Visual Designer',
    'tp1'                       => 'Visual Designer is easy for using but you must follow some rules.',
    'tp2'                       => 'First you complete design for desktop resolution then you adapte other resolutons.',
    'tp3'                       => 'All images you must upload to your server. Visual Designer does not support upload. All assets must be from your server.',
    
    /* Errors ----------------------------------------------------------------- */
    'SaveError'                 => 'There is some errors. Data is not saved. Please try again.',
    'ErrorTitle'                => 'Title can not be empty and can not have special characters!',
    'ErrorName'                 => 'Name can not be empty and is disalowed special characters and html elements',
    'ErrorFirstName'            => "The name was incorrectly entered. Please enter your name.",
    'ErrorLastName'             =>  "The last name was incorrectly entered. Please enter your last name.",
    'ErrorEmail'                =>  "Email is required and can not be empty. Please check is email in the correct format.",
    'ErrorPassword'             =>  "Password is required and can not be empty. Please check is you entered password.",
    'ErrorRPassword'            =>  "Field of repeated password can not be blank and must be the same as the entered password.",
    'ErrorPhone'                => 'Phone number is required. Please add your phone number.',
    'UserLoginError'            => 'User not found. Please check your credential and try again.',
    'ErrorStatus'               => 'Status is required and only numbers allowed!',
    'ErrorPhone2'               => 'In the phone box you need to enter only numbers. Please enter the correct phone number!',
    'ErrorEmail2'               => 'In the email box you need to enter valid email. Please enter the correct email address!',
    'ErrorAddress2'             => 'Address box has ivalid characters. Please add valid address.',
];
