<?php

/**
 * Serbian translation
 */

return [
    
    /*  Form/Route -----------------------------------------------------------  */
    ':keyword'                  => 'keyword',
    ':login'                    => 'login',
    ':registration'             => 'signup',
    ':tutorial'                 => 'uputstva',
    
    'Home'                      => 'Početna',
    'Login'                     => 'Prijava',
    'Login/Registration'        => 'Prijava/Registracija',
    'Registration'              => 'Registracija',
    'UseYourAccount'            => 'Prijavite se vašim nalogom',
    'e-mail'                    => 'E-mail',
    'email'                     => 'email',
    'EnterEmail'                => 'Unesite vašu e-mail adresu',
    'EnterPassword'             => 'Unesite vašu lozinku',
    'ForgotPassword'            => 'Zaboravili ste lozinku?',
    'PasswordRecoveryLink'      => 'Kreiraj novu.',
    'DontHaveAccount'           => 'Nemate nalog?',
    'DontHaveAccountText'       => 'Kreirajte nalog brzo i jednostavno. Kreiranjem naloga omogućujete čuvanje i praćenje visuala kao i drugih informacija.',
    'MakeAccountLink'           => 'Kreiraj nalog',
    'LoginError'                => 'Greška u logovanju',
    'LoginErrorInfo'            => 'Postoji neki greška sa prijavljivanjem. Korisnik ili lozinka nisu ispravni. Unesite ispravne podatke za logovanje i pokušajte ponovo!',
    'LoginSuccess'              => 'Uspešno logovanje',
    'LoginSuccessInfo'          => 'Sada ste uspešno logovani. Molimo sačekajte automatsku redirekciju ili klikom na dugme ispod vratite na početnu stranicu.',
    /* Registration ----------------------------------------------------------- */
    'ReenterPassword'           => 'Ponovite lozinku',
    'name'                      => 'ime',
    'EnterFirstName'            => 'Unesite vaše ime',
    'FirstName'                 => 'Ime',
    'LastName'                  => 'Prezime',
    'Email'                     => 'Email',
    'Password'                  => 'Lozinka',
    'Phone'                     => 'Broj telefona',
    'RPassword'                 => 'Ponovljena lozinka',
    'EnterLastName'             => 'Unesite vaše prezime',
    'UserRegisterSuccessfully'  => 'Uspešno ste završili proces registracije. Kako bi vaš nalog bio aktivan, molimo vas da kliknete na link koji ste dobili na email kako bi verifikovali vašu email adresu.',
    'UserLoginSuccessfully'     => 'Uspešno ste se ulogovali. Molimo sačekajte.',
    'EnterPhone'                => 'Unesite vaš broj telefona',
    'first_name'                => 'first_name',
    'last_name'                 => 'last_name',
    'phone'                     => 'phone',
    'password'                  => 'password',
    'rpassword'                 => 'rpassword',
    /* Designer --------------------------------------------------------------- */
    'NewProject'                => 'Novi projekat',
    'SaveProject'               => 'Sačuvaj',
    'SaveProjectAsNew'          => 'Sačuvaj kao novo',
    'GenerateCode'              => 'Generiši kod',
    'UncategorizedError'        => 'Nastala je greška čiji uzrok nije otkriven. Molimo vas da kontaktirate našu podršku.',
    'DesignSaved'               => 'Projekat je uspešno sačuvan.',
    'TitleError'                => 'Naslov projekta je obavezno polje. Molimo unesite naziv vašeg projekta.',
    'titleplaceholder'          => 'unesi naziv projekta',
    'YourDesigns'               => 'Tvoji dizajni',
    'DesignTitle'               => 'Naziv dizajna',
    'Date'                      => 'Datum',
    'History'                   => 'Istorijat',
    'SignOut'                   => 'Odjava',
    'ContactUs'                 => 'Kontakt',
    'TermsOfUse'                => 'Uslovi korišćenja',
    'Support'                   => 'Podrška',
    'Tutorial'                  => 'Uputstva',
    'Remove'                    => 'Obriši',
    'AddSearchkeywords'         => 'unesi reči za pretragu...',
    'SearchBydate'              => 'pretraži po datumu...',
    'FilterIncluded'            => 'Filter je uključen!',
    'ErrorPhone'                => 'Broj telefona nije ispravan.Molimo vas da uneste ispravan broj telefona.',
    
      /* Registration ----------------------------------------------------------- */
    'ReenterPassword'           => 'Ponovite lozinku',
    'name'                      => 'ime',
    'EnterFirstName'            => 'Unesite vaše ime',
    'FirstName'                 => 'Ime',
    'LastName'                  => 'Prezime',
    'Email'                     => 'Email',
    'Password'                  => 'Lozinka',
    'Phone'                     => 'Broj telefona',
    'RPassword'                 => 'Ponovljena lozinka',
    'EnterLastName'             => 'Unesite vaše prezime',
    'UserRegisterSuccessfully'  => 'Uspešno ste završili proces registracije. Kako bi vaš nalog bio aktivan, molimo vas da kliknete na link koji ste dobili na email kako bi verifikovali vašu email adresu.',
    'UserLoginSuccessfully'     => 'Uspešno ste se ulogovali. Molimo sačekajte.',
    'EnterPhone'                => 'Unesite vaš broj telefona',
    'first_name'                => 'first_name',
    'last_name'                 => 'last_name',
    'phone'                     => 'phone',
    'password'                  => 'password',
    'rpassword'                 => 'rpassword',
    'RegistrationSuccess'       => 'Uspešno ste se registrovali.',
    'successreginfo'            => 'Molimo sačekajte da web administrator aktivira vaš nalog.',
    
    'PageNotFound'              => 'SStranica nnije pronađena. Molimo proverite URL adresu i pokušajte ponovo!',
    
    /* Pages ------------------------------------------------------------------ */
    'VisualDesignerAbout'       => 'O alatu za kreiranje grafičkih stranica',
    'tp1'                       => 'Visual Designer je jednostavan za korišćenje ali morate ispoštovati nekoliko pravila.',
    'tp2'                       => 'Prvo kompletirajte stranicu za desktop prikaz pa tek onda uredite ostale rezolucije.',
    'tp3'                       => 'Sve slike moraju biti prethodno uploadovane na vašem serveru. Visual Designer ne podržava upload slika. Svi aseti moraju biti na vašem serveru.',
    
     /* Errors ----------------------------------------------------------------- */
    'SaveError'                 => 'Došlo je do greške prilikom snimanja. Molimo vas da pokušate ponovo.',
    'ErrorTitle'                => 'Naslov ne može biti prazan ili sadržavati specijalne znake!',
    'ErrorName'                 => 'Ime ne može biti prazno ili sadržavati specijalne karaktere kao ni html elemente.',
    'ErrorFirstName'            => "Ime je obavezno polje i ne može biti prazno. Proverite da li ste ispravno uneli vaše ime.",
    'ErrorLastName'             => "Prezime je obavezno polje i ne može biti prazno. Proverite da li ste ispravno uneli vaše prezime.",
    'ErrorEmail'                => "Email je obavezno polje i mora biti uneto u ispravnom formatu. Proverite da li ste ispravno uneli vašu email adresu.",
    'ErrorPassword'             => "Lozinka je obavezno polje i ne može biti prazno. proverite da li ste uneli vašu novu lozinku.",
    'ErrorRPassword'            => "Polje za ponovljenu lozinku ne može ostati prazno i mora biti ista kao i uneta lozinka.",
    'UserLoginError'            => 'Korisnik nije pronađen. Proverite da li ispravno unosite vašu e-mail i lozinku i pokušajte ponovo.',
    'ErrorPhone'                => 'Broj telefona je obavezno polje. Molimo vas da uneste  vaš broj telefona.',
    'ErrorStatus'               => 'Status je obavezno polje i samo unos brojeva je dozvoljeno!',
    'ErrorPhone2'               => 'U polje za telefon morate uneti samo brojeve. Molimo da ispravno unesete broj telefona!',
    'ErrorEmail2'               => 'U polje za email morate uneti validnu email adresu. Molimo da ispravno unesete email!',
    'ErrorAddress2'             => 'Adresa sadrži nedozvoljene karaktere. Molimo da unesete ispravnu adresu!',
];
