<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/favicon.ico">

    <title>Title</title>
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,500,700,300&amp;subset=latin,latin-ext,cyrillic" rel="stylesheet">
    <?= Minty\Assets\AssetsController::CSS() ?>
  </head>

  <body>
      
      <header>
          <a href="<?=site_url()?>" class="logo"><img src="<?=assets_url('assets/img/layout/logo.jpg')?>" /></a>
          <?php echo $this->getServiceLocator()->get('NavigationHelper')->html() ?>
      </header>

      <?php echo $ViewModel->html(); ?>
      
      <footer>
          <div class="footer-wrap clear">
              <?php if(0>1):?>
              <a href="<?=site_url()?>" class="logo"><img src="<?=assets_url('assets/img/layout/logo-black.png')?>" /></a>
              <?php endif;?> 
              <div class="footer-links clear">
                  <?php if(Minty\MVC::getUserData() ):?> 
                  <a href="<?= site_url('logout')?>" class="pull-left"><?=language('SignOut')?></a> 
                  <a href="<?= Minty\Router::FromRoute('Imedia\Designer', 'history')?>" class="pull-left"><?=language('History')?></a> 
                  <?php endif;?> 
                  <a href="" class="pull-right"><?=language('ContactUs')?></a>
                  <a href="" class="pull-right"><?=language('TermsOfUse')?></a>
                  <a href="" class="pull-right"><?=language('Support')?></a>
                  <a href="<?= Minty\Router::FromRoute('Imedia\Pages', 'tutorial')?>" class="pull-right"><?=language('Tutorial')?></a>
              </div>
          </div>
      </footer>
      
      <?php echo Minty\Application::$Profiler; ?>
      
      
      <?= Minty\Assets\AssetsController::JS() ?>
      <script src="<?=assets_url('assets/js/jquery-ui.min.js')?>"></script>
      <script src="<?=assets_url('assets/plugins/tinymce_4.5.4/js/tinymce/tinymce.min.js')?>"></script>
  </body>
</html>