<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/favicon.ico">

    <title>Administrator login</title>
    
    <?= Minty\Assets\AssetsController::CSS() ?>
  </head>

  <body>

      <?php echo $ViewModel->html(); ?>
      
      
      <script>
          var site_url = '<?=site_url('backside');?>';
      </script>
      <?= Minty\Assets\AssetsController::JS() ?>
      
  </body>
</html>